<a href="https://colab.research.google.com/github/pericrea-dotcom/kolegij-AI-znanosti-/blob/main/predavanje_dan_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
12

12

In [ ]:
type(12)

int

In [ ]:
type(12.5)

float

In [ ]:
type("lana")

str

In [ ]:
"apple"

'apple'

In [ ]:
True

True

In [ ]:
False

False

In [ ]:
3<5

True

In [ ]:
7<2

False

In [ ]:
[1,2,3]

[1, 2, 3]

In [ ]:
type([1,2,3])

list

In [ ]:
1,2,3

(1, 2, 3)

In [ ]:
t = [1,2,3]

In [ ]:
t

[1, 2, 3]

In [ ]:
plants = {"apple": "a fruit", "banana": "a herb"}

In [ ]:
type ({"apple": "a fruit", "banana": "a herb"})

dict

In [ ]:
plants

{'apple': 'a fruit', 'banana': 'a herb'}

In [ ]:
plants["banana"]

'a herb'

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(plants, [0,1])

apple  banana
0  a fruit  a herb
1  a fruit  a herb

In [ ]:
squares = [1,4,9,16,25]

In [ ]:
type(squares
    )

list

In [ ]:
squares

[1, 4, 9, 16, 25]

In [ ]:
squares [4]

25

In [ ]:
squares[-2]

16

In [ ]:
squares[:]

[1, 4, 9, 16, 25]

: označi od kud do kud da printa listu

In [ ]:
squares[1:]

[4, 9, 16, 25]

sad 1. makne tj. nultog kad si broji od nule, 1 je njemu u biti 2, do zadnjeg jer nema ništa na zadnjem mjestu

In [ ]:
squares[1:3]


[4, 9]

opet makne 1. tj. nulti, ostavi 1 ali makne 3.

In [ ]:
squares + [36,49,64,81,100]


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
squares

[1, 4, 9, 16, 25]

In [ ]:
sq2 = squares + [36,49,64,81,100]


In [ ]:
sq2

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
animals = ["cat", "dog","bird"]

In [ ]:
animals [0]

'cat'

In [ ]:
len(sq2)

10

In [ ]:
len(sq2[:5])

5

In [ ]:
letters = ['a','b','c','d','e','f','g']

In [ ]:
letters

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [ ]:
letters[1:2]=[1,2,3,4,5]
letters

['a', 1, 2, 3, 4, 5, 'c', 'd', 'e', 'f', 'g']

In [ ]:
len(letters)

11

In [ ]:
abs(1)

1

In [ ]:
abs(-10)

10

abs je apsolutna vrijednost

In [ ]:
import operator

In [ ]:
1+3

4

In [ ]:
operator.add (1,3)

4

In [ ]:
operator.sub(1,10)

-9

In [ ]:
operator.eq(1,10)

False

In [ ]:
operator.eq(10,10)

True

In [ ]:
#print

In [ ]:
print(1)

1


In [198]:
print('This'+' '+'is'+' '+'a'+' '+'full'+' '+'sentence')

This is a full sentence


In [ ]:
print('This', 'is', 'a', 'full', 'sentence')

This is a full sentence


In [ ]:
print('Michael', 'is','helping')

Michael is helping


In [ ]:
print(sq2[1:5])

[4, 9, 16, 25]


In [ ]:
sq2

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
None

In [ ]:
type(None)

NoneType

In [61]:
##funkcije


In [63]:
def our_function(x):
  '''This function multiplies its argument by 2.
  Writen by Lana'''
  result = x*2
  return result

In [64]:
our_function(5)

10

In [66]:
our_function(3.14)

6.28

In [67]:
type(our_function)

function

In [68]:
import math

In [69]:
def ph(c):
  '''Ova f-ja računa pH otopina.
  koristi koncentraciju H+ in mol/L.
  vraća pH.'''
  ph_value = -math.log10(c)
  return ph_value

za veće f-je ovak preporuča, da je lakše, da znamo kaj smo radili, ph_value naša interna oznaka, to smo mogli nazvat žnj

In [70]:
ph(0.001)

3.0

In [71]:
def ph1(c):
  return -math.log10(c)

In [72]:
ph1(0.001)

3.0

In [199]:
def task(x,y):
  '''definicija'''
  print('This is the log10 of x', math.log10(x))
  print('This is the log10 of y', math.log10(y))
  new_number = math.log10(x) + math.log10(y)
  print('The result is below:')
  return new_number

In [201]:
task(1000, 2.73)

This is the log10 of x 3.0
This is the log10 of y 0.436162647040756
The result is below:


3.436162647040756

In [202]:
def konv_eur(euro):
  dkk = euro*7.55
  return dkk

In [203]:
konv_eur(10)

75.5

In [81]:
def plus(a,b,c,d):
  suma = a+b+c+d
  return suma

In [274]:
def plus1(a,pero,c,d):
  suma = a+pero+c+d
  return suma

In [272]:
plus(3,4,5,6)

18

In [275]:
plus1(2,4,6,8)

20

In [85]:
plus(3,4,100,1000)

1107

In [87]:
# = i ==

In [89]:
1==1

True

In [90]:
k=(1,2,3)

In [91]:
type(k)

tuple

In [276]:
width =20
height = 5*90
height, width

(450, 20)

In [277]:
cp1 = 'tomo'
cp2 = 'marija'
cp1,cp2

('tomo', 'marija')

In [278]:
width==height

False

In [280]:
width == 30

False

In [279]:
width=height

In [281]:
width ==20

False

In [284]:
width = 30

dopisivala sam kasnije pa sam malo zamijenila redoslijed, ugl. kada smo sada tu definirali da je w=30 gore kada bi gore ponovo pokrenuli w==30 dobili bi true, sad je sve false jer sam prvo pozvala w=h...


In [95]:
cp1==cp2

False

In [96]:
cp1 != cp2

True

In [97]:
# is i is not

In [98]:
5 is 4

<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
/tmp/ipython-input-519160097.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  5 is 4


False

In [99]:
5 is 5

<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
/tmp/ipython-input-1783323536.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  5 is 5


True

In [285]:
width is height

False

In [286]:
width is not height

True

In [102]:
squares


[1, 4, 9, 16, 25]

In [103]:
squares.append(36)

In [104]:
squares

[1, 4, 9, 16, 25, 36]

In [106]:
squares_part2=squares+[36]

In [107]:
squares_part2


[1, 4, 9, 16, 25, 36, 36]

In [289]:
new_list.append(49)
squares_part2.append(49)

NameError: name 'new_list' is not defined

In [109]:
last_list= squares.copy()

In [110]:
last_list

[1, 4, 9, 16, 25, 36]

In [111]:
squares.append(10)
last_list

[1, 4, 9, 16, 25, 36]

In [112]:
squares


[1, 4, 9, 16, 25, 36, 10]

In [113]:
print('sudionici u korsu su bili', cp1, 'i', cp2,'.')

sudionici u korsu su bili tomo i marija .


In [114]:
print('sudionisi u korsu su bili %s i %s.')

sudionisi u korsu su bili %s i %s.


In [115]:
print('sudionisi u korsu su bili %s i %s.'
%(cp1,cp2))

sudionisi u korsu su bili tomo i marija.


In [116]:
print('sudionisi u korsu su bili $s i $s.'
$(cp1,cp2))

SyntaxError: invalid syntax (ipython-input-2382453566.py, line 2)

ovo je samo proba jer je prof. zabunom govorila "dolarići"

In [293]:
sample = 'u552'
conc = 0.002
print('u uzorku %s našli smo %s mg/L droga' %(samlpe,conc))

NameError: name 'samlpe' is not defined

In [292]:
sample = 'u552'
conc = 0.002
print('in a sample %s we found %s mg/L of drugs' %(sample, conc))

in a sample u552 we found 0.002 mg/L of drugs


In [294]:
print(f'In a sample {sample} we found {conc} mg/L of drugs.')

In a sample u552 we found 0.002 mg/L of drugs.


In [295]:
sample = 'u553'
conc = 0.016
print('in a sample %s we found %s mg/L of drugs' %(sample, conc))

in a sample u553 we found 0.016 mg/L of drugs


In [119]:
def bmi(w,h):
  bmi=w/h**2
  return bmi

In [120]:
bmi (w=68, h=1.62)

25.910684346898332

In [121]:
bmi(68,1.62)

25.910684346898332

In [122]:
#c1*v1=c2*v2


In [123]:
def diluter(c1,v1=1,v2=2):
  '''racuna razrjeđenja
  vraća c2'''
  c2=c1*v1/v2
  return c2

In [125]:
diluter ()


TypeError: diluter() missing 1 required positional argument: 'c1'

ili u zagradu ulazne elemente kad zovemo ili gore isto možemo i c1 def

---



In [126]:
diluter(0.5,1,2)

0.25

In [127]:
help(diluter)

Help on function diluter in module __main__:

diluter(c1, v1=1, v2=2)
    racuna razrjeđenja
    vraća c2



In [128]:
diluter(2)

1.0

In [129]:
diluter (2,1,3)

0.6666666666666666

uzme u obzir nove brojeve bez obzira na one gore zadane

In [130]:
def factor_corrections(c, f=1):
  conc=c*f
  return conc

In [131]:
factor_corrections(0.0002)

0.0002

In [136]:
def do_something_else(a=1, b=2, c=3):
 return (a, b, c)

In [138]:
do_something_else()


(1, 2, 3)

In [296]:
do_something_else(10,10)

(10, 10, 3)

In [297]:
do_something(10,10)

NameError: name 'do_something' is not defined

In [139]:
do_something_else (5,5,c=5)

(5, 5, 5)

In [140]:
do_something_else (a=10)

(10, 2, 3)

In [143]:
def suma(a,b):
  return a+b
def adding_3rd(a,b,c):
  return suma(a,b) + c
adding_3rd(1,2,3)

6

In [144]:
#for


In [145]:
my_friends = ['Mihael', 'Tomo','Maria', 'Petar']


In [146]:
for person in my_friends:
  print (person)

Mihael
Tomo
Maria
Petar


In [147]:
for friends in my_friends:
  print (friends)


Mihael
Tomo
Maria
Petar


In [148]:
for x in my_friends:
  print (x)

Mihael
Tomo
Maria
Petar


In [152]:
def bmi (w,h):
  bmi =w/h**2
  return bmi

In [162]:
težine = [80,90,55,70]
visine =[1.8, 2.0,1.6,1.55]

for x, friend in enumerate(my_friends):
    bmi_person = bmi(težine[x], visine[x])

    print(f'{friend} ima BMI od {bmi_person}.')

Mihael ima BMI od 24.691358024691358.
Tomo ima BMI od 22.5.
Maria ima BMI od 21.484374999999996.
Petar ima BMI od 29.1363163371488.


In [163]:
print(f'{friend} ima BMI od {bmi_person}.')

Petar ima BMI od 29.1363163371488.


In [164]:
bmi_person


29.1363163371488

ova dva naćina izbacuju samo zadnju stavku

In [169]:
squares = [1,4,9,16,25]

In [170]:
for x in squares:
  print('element je %s'%x)

element je 1
element je 4
element je 9
element je 16
element je 25


In [171]:
for number in squares:
  print(number)

1
4
9
16
25


In [172]:
sudionici_kursa = [cp1, cp2]

In [173]:
sudionici_kursa

['tomo', 'marija']

In [174]:
for name in sudionici_kursa:
  print(name)

tomo
marija


In [176]:
for n in sudionici_kursa:
  print(n)

tomo
marija


In [178]:
for pozicija in range(len(sudionici_kursa)):
  print(pozicija)

0
1


tu si možemo samo pos za position

In [179]:
for number, element in enumerate(squares):
  print (number, element)

0 1
1 4
2 9
3 16
4 25


In [180]:
squares

[1, 4, 9, 16, 25]

In [182]:
for number in squares:
  sq_root = math.sqrt(number)
  print(sq_root)

1.0
2.0
3.0
4.0
5.0


if else


In [183]:
1<=2

True

In [184]:
if 1 ==1:
  print('yes')
  print('da')
  print('ja')
  print('oui')

yes
da
ja
oui


In [189]:
if 1 == 2:
  print('yes')
  print('da')
  print('ja')
  print('oui')

In [190]:
1==2

False

In [192]:
cp1= 'Mila'
cp2='Marko'

In [195]:
if cp1==cp2:
  print('da')

In [196]:
if cp1!=cp2:
  print('jup')

jup


In [197]:
if cp1==cp2:
  print('da')
else:
  print('ne')

ne


In [205]:
def check_gender_by_name(name):
  if name [-1] =='a':
    gender ='female'
  elif name[-1] =='o':
    gender = 'male'
  else:
    gender = 'nepoznato'
  return gender

In [206]:
check_gender_by_name ('lana')

'female'

In [207]:
check_gender_by_name ('lan')

'nepoznato'

In [208]:
check_gender_by_name('Marko')

'male'

In [209]:
def ph(c):
  return -math.log10(c)

In [210]:
ph(0.001)

3.0

In [213]:
def ph_evaluator(c=0.001):
  '''pH decision maker'''
  ph_val = ph(c)
  if ph_val < 7:
    decision = 'kileslo'
  else:
    decision = 'lužnato'
  return decision
ph_evaluator (0.0001)

'kileslo'

In [214]:
ph_evaluator()

'kileslo'

In [216]:
def ph_evaluator(c=0.001):
  if ph(c)<7:
    return 'kiselo'
  else:
   return 'lužnato'

conc_list = [0.001,0.01,0.1,1,10]
for solution in conc_list:
  print(ph_evaluator(solution))

kiselo
kiselo
kiselo
kiselo
kiselo


In [221]:
def test_if_else(a,b):
  '''
  a,b su argumenti
  return 'a > b' or 'a is not > b'
  '''
  if a>b:
    print(a, '>', b)
  else:
    print('%d is not > %d' %(a,b))

In [222]:
help(test_if_else)

Help on function test_if_else in module __main__:

test_if_else(a, b)
    a,b su argumenti
    return 'a > b' or 'a is not > b'



In [223]:
test_if_else(2,6)

2 is not > 6


In [224]:
test_if_else(6,2)

6 > 2


In [225]:
test_if_else(2,'Lana')

TypeError: '>' not supported between instances of 'int' and 'str'

In [226]:
def rectangle_area(a,b):
  '''dokumentacija'''
  A=a*b
  if a==b:
    print('kvadrat')
  else:
    print('pravokutnik')
  return A

In [227]:
rectangle_area(2,3)

pravokutnik


6

In [228]:
rectangle_area(8,8)

kvadrat


64

In [229]:
rectangle_area

<function __main__.rectangle_area(a, b)>

In [230]:
for letter in [1,2,3]:
  print ('broj: ', letter)

broj:  1
broj:  2
broj:  3


In [299]:
x=5

In [302]:
x

7

kad smo dolje def da je x=7 i pokrenuli zapamti to i onda kad pokrenemo tu di je samo x zato ispise 7

In [301]:
x=7

In [303]:
y=2

In [304]:
x+y

9

In [305]:
povrsina=rectangle_area(5,4)

pravokutnik


In [306]:
povrsina


20

In [307]:
-(3**4)

-81

In [308]:
3*3.75/1.5

7.5

In [237]:
a = [4,5,6]
n=[1,2,3]

In [238]:
x = [a,n]

In [239]:
x

[[4, 5, 6], [1, 2, 3]]

način za napravit jednostavniju matricu

In [240]:
import numpy as np



In [242]:
nums1 = [1,2,3,4,5]
nums1

[1, 2, 3, 4, 5]

In [243]:
nums2=np.array(nums1)

In [244]:
nums2

array([1, 2, 3, 4, 5])

In [245]:
type(nums1), type(nums2)

(list, numpy.ndarray)

In [246]:
max(nums1)

5

In [247]:
min(nums1)

1

In [248]:
np.min(nums1)

np.int64(1)

In [250]:
x1= np.array ([1.3,0,2])
x1

array([1.3, 0. , 2. ])

In [251]:
x2 = np.array([1,0,2])
x2

array([1, 0, 2])

In [252]:
type(x1), type(x2)

(numpy.ndarray, numpy.ndarray)

In [253]:
x1.dtype

dtype('float64')

In [254]:
x2.dtype

dtype('int64')

In [255]:
x2 = np.arange (20,50,2)
x2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [256]:
x2 = np.arange (20,50,3)
x2

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [257]:
np.linspace(10,20,10, endpoint=True)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [259]:
np.linspace(10,20,10, endpoint=False)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [261]:
nule = np.zeros((5,3))
nule.shape

(5, 3)

In [262]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [264]:
x4=np.random.random((3,10))
x4

array([[0.62940114, 0.38923308, 0.34697996, 0.56026555, 0.06044299,
        0.34299398, 0.97642272, 0.12566611, 0.27087488, 0.06671266],
       [0.48244992, 0.14941555, 0.96794043, 0.14607147, 0.38968759,
        0.55482568, 0.90838923, 0.76721293, 0.98002402, 0.49472483],
       [0.4100754 , 0.26933954, 0.92517154, 0.48806612, 0.15483737,
        0.01170927, 0.51789093, 0.15968215, 0.68397381, 0.74583039]])

In [265]:
pd.DataFrame(x4)

0         1         2         3         4         5         6  \
0  0.629401  0.389233  0.346980  0.560266  0.060443  0.342994  0.976423   
1  0.482450  0.149416  0.967940  0.146071  0.389688  0.554826  0.908389   
2  0.410075  0.269340  0.925172  0.488066  0.154837  0.011709  0.517891   

          7         8         9  
0  0.125666  0.270875  0.066713  
1  0.767213  0.980024  0.494725  
2  0.159682  0.683974  0.745830

In [266]:
x4.dtype

dtype('float64')

In [267]:
x4.shape

(3, 10)

In [268]:
x4.reshape(10,3)

array([[0.62940114, 0.38923308, 0.34697996],
       [0.56026555, 0.06044299, 0.34299398],
       [0.97642272, 0.12566611, 0.27087488],
       [0.06671266, 0.48244992, 0.14941555],
       [0.96794043, 0.14607147, 0.38968759],
       [0.55482568, 0.90838923, 0.76721293],
       [0.98002402, 0.49472483, 0.4100754 ],
       [0.26933954, 0.92517154, 0.48806612],
       [0.15483737, 0.01170927, 0.51789093],
       [0.15968215, 0.68397381, 0.74583039]])

In [269]:
x4.T

array([[0.62940114, 0.48244992, 0.4100754 ],
       [0.38923308, 0.14941555, 0.26933954],
       [0.34697996, 0.96794043, 0.92517154],
       [0.56026555, 0.14607147, 0.48806612],
       [0.06044299, 0.38968759, 0.15483737],
       [0.34299398, 0.55482568, 0.01170927],
       [0.97642272, 0.90838923, 0.51789093],
       [0.12566611, 0.76721293, 0.15968215],
       [0.27087488, 0.98002402, 0.68397381],
       [0.06671266, 0.49472483, 0.74583039]])

transpose

In [311]:
np.arange(2,20).reshape(2,3,3).T

array([[[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]],

       [[ 4, 13],
        [ 7, 16],
        [10, 19]]])

In [313]:
I=np.eye (3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [315]:
from numpy import reshape
from numpy._core.multiarray import arange
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [316]:
I=np.eye(3)
I@A

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [317]:
A@A

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])